INSERT INTO category (name) VALUES ('Groceries');
INSERT INTO category (name) VALUES ('Fuel');
INSERT INTO category (name) VALUES ('Clothes');
INSERT INTO category (name) VALUES ('Utilities');
INSERT INTO category (name) VALUES ('Entertainment');
INSERT INTO category (name) VALUES ('Transportation');
INSERT INTO category (name) VALUES ('Healthcare');
INSERT INTO category (name) VALUES ('Education');
INSERT INTO category (name) VALUES ('Dining Out');
INSERT INTO category (name) VALUES ('Travel');
